services:
  datastore:
    image: ghcr.io/hanzoai/datastore:latest
    user: "101:101"
    environment:
      DATASTORE_DB: default
      DATASTORE_USER: ${DATASTORE_USER:-hanzo}
      DATASTORE_PASSWORD: ${DATASTORE_PASSWORD:-hanzo}
    volumes:
      - hanzo_datastore_data:/var/lib/datastore
      - hanzo_datastore_logs:/var/log/datastore
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - postgres

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - "10000:10000"
    volumes:
      - hanzo_azurite_data:/data

  s3:
    image: ghcr.io/hanzoai/s3:latest
    container_name: ${S3_CONTAINER_NAME:-hanzo-s3}
    entrypoint: sh
    # create the 'hanzo' bucket before starting the service
    command: -c 'mkdir -p /data/hanzo && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniosecret}
    ports:
      - ${HOST_IP:-127.0.0.1}:${S3_API_PORT:-9090}:9000
      - ${HOST_IP:-127.0.0.1}:${S3_CONSOLE_PORT:-9091}:9001
    volumes:
      - hanzo_s3_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
    networks:
      - default

  redis:
    image: docker.io/redis:7.2.4
    restart: always
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
      --maxmemory-policy noeviction
    ports:
      - 6379:6379

  postgres:
    image: docker.io/postgres:${POSTGRES_VERSION:-17}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=UTC
      - PGTZ=UTC
    ports:
      - 5432:5432
    volumes:
      - hanzo_postgres_data:/var/lib/postgresql/data

volumes:
  hanzo_postgres_data:
    driver: local
  hanzo_datastore_data:
    driver: local
  hanzo_datastore_logs:
    driver: local
  hanzo_azurite_data:
    driver: local
  hanzo_s3_data:
    name: ${S3_VOLUME_NAME:-hanzo_s3_data}
    driver: local
