services:
  # hanzo-web:
  #   build:
  #     dockerfile: ./web/Dockerfile
  #     context: .
  #     args:
  #       - NEXT_PUBLIC_HANZO_CLOUD_REGION=${NEXT_PUBLIC_HANZO_CLOUD_REGION}
  #   depends_on: &hanzo-depends-on
  #     postgres:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     clickhouse:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"
  #   environment: &hanzo-web-env
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  #     NEXTAUTH_SECRET: mysecret
  #     SALT: mysalt
  #     ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000" # generate via `openssl rand -hex 32`
  #     NEXTAUTH_URL: http://localhost:3000
  #     TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-true}
  #     HANZO_ENABLE_EXPERIMENTAL_FEATURES: ${HANZO_ENABLE_EXPERIMENTAL_FEATURES:-false}
  #     HANZO_INIT_ORG_ID: ${HANZO_INIT_ORG_ID:-}
  #     HANZO_INIT_ORG_NAME: ${HANZO_INIT_ORG_NAME:-}
  #     HANZO_INIT_ORG_IDS: ${HANZO_INIT_ORG_IDS:-}
  #     HANZO_INIT_ORG_NAMES: ${HANZO_INIT_ORG_NAMES:-}
  #     HANZO_INIT_PROJECT_ID: ${HANZO_INIT_PROJECT_ID:-}
  #     HANZO_INIT_PROJECT_ORG_ID: ${HANZO_INIT_PROJECT_ORG_ID:-}
  #     HANZO_INIT_PROJECT_NAME: ${HANZO_INIT_PROJECT_NAME:-}
  #     HANZO_INIT_PROJECT_PUBLIC_KEY: ${HANZO_INIT_PROJECT_PUBLIC_KEY:-}
  #     HANZO_INIT_PROJECT_SECRET_KEY: ${HANZO_INIT_PROJECT_SECRET_KEY:-}
  #     HANZO_INIT_USER_EMAIL: ${HANZO_INIT_USER_EMAIL:-}
  #     HANZO_INIT_USER_NAME: ${HANZO_INIT_USER_NAME:-}
  #     HANZO_INIT_USER_PASSWORD: ${HANZO_INIT_USER_PASSWORD:-}
  #     CLICKHOUSE_MIGRATION_URL: ${CLICKHOUSE_MIGRATION_URL:-clickhouse://clickhouse:9000}
  #     CLICKHOUSE_URL: ${CLICKHOUSE_URL:-http://clickhouse:8123}
  #     CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
  #     CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse}
  #     CLICKHOUSE_CLUSTER_ENABLED: ${CLICKHOUSE_CLUSTER_ENABLED:-false}
  #     HANZO_S3_EVENT_UPLOAD_BUCKET: ${HANZO_S3_EVENT_UPLOAD_BUCKET:-hanzo}
  #     HANZO_S3_EVENT_UPLOAD_REGION: ${HANZO_S3_EVENT_UPLOAD_REGION:-us-east-1}
  #     HANZO_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${HANZO_S3_EVENT_UPLOAD_ACCESS_KEY_ID:-minio}
  #     HANZO_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${HANZO_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}
  #     HANZO_S3_EVENT_UPLOAD_ENDPOINT: ${HANZO_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9000}
  #     HANZO_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: ${HANZO_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}
  #     HANZO_S3_EVENT_UPLOAD_PREFIX: ${HANZO_S3_EVENT_UPLOAD_PREFIX:-events/}
  #     REDIS_HOST: ${REDIS_HOST:-redis}
  #     REDIS_PORT: ${REDIS_PORT:-6379}
  #     REDIS_AUTH: ${REDIS_AUTH:-myredissecret}
  #     REDIS_TLS_ENABLED: ${REDIS_TLS_ENABLED:-false}
  #     REDIS_TLS_CA: ${REDIS_TLS_CA:-/certs/ca.crt}
  #     REDIS_TLS_CERT: ${REDIS_TLS_CERT:-/certs/redis.crt}
  #     REDIS_TLS_KEY: ${REDIS_TLS_KEY:-/certs/redis.key}
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000/api/public/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  hanzo-worker:
    image: hanzoai/cloud-worker:3.38.0
    restart: always
    build:
      dockerfile: ./worker/Dockerfile
      context: .
      args:
        - NEXT_PUBLIC_HANZO_CLOUD_REGION=${NEXT_PUBLIC_HANZO_CLOUD_REGION}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    ports:
      - "3030:3030"
    environment:
      # <<: *hanzo-web-env
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
      ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000" # generate via `openssl rand -hex 32`
      NEXTAUTH_URL: http://localhost:3000
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-true}
      HANZO_ENABLE_EXPERIMENTAL_FEATURES: ${HANZO_ENABLE_EXPERIMENTAL_FEATURES:-false}
      HANZO_INIT_ORG_ID: ${HANZO_INIT_ORG_ID:-}
      HANZO_INIT_ORG_NAME: ${HANZO_INIT_ORG_NAME:-}
      HANZO_INIT_ORG_IDS: ${HANZO_INIT_ORG_IDS:-}
      HANZO_INIT_ORG_NAMES: ${HANZO_INIT_ORG_NAMES:-}
      HANZO_INIT_PROJECT_ID: ${HANZO_INIT_PROJECT_ID:-}
      HANZO_INIT_PROJECT_ORG_ID: ${HANZO_INIT_PROJECT_ORG_ID:-}
      HANZO_INIT_PROJECT_NAME: ${HANZO_INIT_PROJECT_NAME:-}
      HANZO_INIT_PROJECT_PUBLIC_KEY: ${HANZO_INIT_PROJECT_PUBLIC_KEY:-}
      HANZO_INIT_PROJECT_SECRET_KEY: ${HANZO_INIT_PROJECT_SECRET_KEY:-}
      HANZO_INIT_USER_EMAIL: ${HANZO_INIT_USER_EMAIL:-}
      HANZO_INIT_USER_NAME: ${HANZO_INIT_USER_NAME:-}
      HANZO_INIT_USER_PASSWORD: ${HANZO_INIT_USER_PASSWORD:-}
      CLICKHOUSE_MIGRATION_URL: ${CLICKHOUSE_MIGRATION_URL:-clickhouse://clickhouse:9000}
      CLICKHOUSE_URL: ${CLICKHOUSE_URL:-http://clickhouse:8123}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse}
      CLICKHOUSE_CLUSTER_ENABLED: ${CLICKHOUSE_CLUSTER_ENABLED:-false}
      HANZO_S3_EVENT_UPLOAD_BUCKET: ${HANZO_S3_EVENT_UPLOAD_BUCKET:-hanzo}
      HANZO_S3_EVENT_UPLOAD_REGION: ${HANZO_S3_EVENT_UPLOAD_REGION:-us-east-1}
      HANZO_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${HANZO_S3_EVENT_UPLOAD_ACCESS_KEY_ID:-minio}
      HANZO_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${HANZO_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}
      HANZO_S3_EVENT_UPLOAD_ENDPOINT: ${HANZO_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9000}
      HANZO_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: ${HANZO_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}
      HANZO_S3_EVENT_UPLOAD_PREFIX: ${HANZO_S3_EVENT_UPLOAD_PREFIX:-events/}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_AUTH: ${REDIS_AUTH:-myredissecret}
      REDIS_TLS_ENABLED: ${REDIS_TLS_ENABLED:-false}
      REDIS_TLS_CA: ${REDIS_TLS_CA:-/certs/ca.crt}
      REDIS_TLS_CERT: ${REDIS_TLS_CERT:-/certs/redis.crt}
      REDIS_TLS_KEY: ${REDIS_TLS_KEY:-/certs/redis.key}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-dev

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - hanzo_clickhouse_data:/var/lib/clickhouse
      - hanzo_clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
    networks:
      - local-dev

  minio:
    image: minio/minio
    entrypoint: sh
    # create the 'hanzo' bucket before starting the service
    command: -c 'mkdir -p /data/hanzo && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "9090:9000"
      - "9091:9001"
    volumes:
      - hanzo_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
    networks:
      - local-dev

  redis:
    image: redis:7
    restart: always
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - local-dev
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - hanzo_postgres_data:/var/lib/postgresql/data
    networks:
      - local-dev

volumes:
  hanzo_postgres_data:
    driver: local
  hanzo_clickhouse_data:
    driver: local
  hanzo_clickhouse_logs:
    driver: local
  hanzo_minio_data:
    driver: local


networks:
  local-dev:
